### ISSUE TITLE
Log messages truncated by the UI

### ISSUE THREAD

**Issue by jared-wallace** [jaegertracing/jaeger-ui#148]
**Description**
Log messages in the UI are truncated, and there is no scroll bar to view the portion not contained in the box.

**Steps to reproduce the issue:**
1. Report a long log message to a span
2. View the span in the UI, and see that the log message is truncated

**Describe the results you received:**
The only way to view the entire log message is to use developer tools to inspect the element.

**Describe the results you expected:**
I'd expect to be able to scroll horizontally to view the entire log message.

**Additional information you deem important (e.g. issue happens only occasionally):**
I would imagine this is a simple fix, but I'm not a UI person by any means, so maybe not.

**Additional environment details (Browser, etc.):**
Chrome version 63.0.3239.108 (Official Build) (64-bit)
OSX High Sierra
Using the Jaeger all-in-one container(latest)

**Comment by tiffon** [comment]
Thanks for filing this. Definitely long values should be scrollable with whitespace preserved.

**Comment by tiffon** [comment]
I wasn't able to reproduce this. Can you send a screenshot?

One thing worth noting is the [+] icon next to each log message indicates the log message can be expanded. And, clicking anywhere on the log message expands it into a table of key/value pairs. The table should scroll for long values:

<img width="768" alt="screen shot 2017-12-23 at 3 42 52 am" src="https://user-images.githubusercontent.com/2304337/34318353-968a06ce-e793-11e7-96e7-f0a4cdfb270c.png">

**Comment by jared-wallace** [comment]
Here's what I see:
![selection_022 1](https://user-images.githubusercontent.com/6503051/34319630-cc2c09c6-e7ac-11e7-8be0-196d7ac6021e.png)

**Comment by jared-wallace** [comment]
Here's what I see:
![selection_022 2](https://user-images.githubusercontent.com/6503051/34319638-fae62b0c-e7ac-11e7-999f-029c0ee6c34d.png)

**Comment by tiffon** [comment]
@jared-wallace Thanks for the screenshot.

Looks like the docker image is out of date. This issue was resolved a few months ago. One indication that the image is out of date is the `[+] Debug Info` button in the lower left corner of the span detail section.

The latest `jaegertracing/all-in-one` image was created a few hours ago. Mind giving it a shot?

```shell
$ docker images | grep jaegertracing/all-in-one
jaegertracing/all-in-one   latest              edcf7b4540c3        4 hours ago         46.1MB
```

**Comment by jared-wallace** [comment]
Hmm. I did a `docker-compose pull jaeger`, and it acted like it pulled a newer image, but I still see the same issue (and the tell-tale [+] Debug).

Output from pull:
```
Pulling jaeger (jaegertracing/all-in-one:latest)...
latest: Pulling from jaegertracing/all-in-one
b76078f6badb: Pull complete
d84e754e6a7a: Pull complete
Digest: sha256:dcde5441f81a92c810e265709c6e9bb9c25dab569801fc9af87e354797d65565
Status: Downloaded newer image for jaegertracing/all-in-one:latest
```

My docker compose is:
```
jaeger:
      image: jaegertracing/all-in-one:latest
      container_name: jaeger
```

Using VS Code to inspect the image, the ID sha is `sha256:edcf7b4540c3d1801e184932a59a0e168d2107bd16e8acaec04eded2de2b02f9`
and the image sha is `sha256:b229e8f3c8a945d36dbbdbf0ae92760497e61e9b32fd9e0a03e498a75d0ade27"`

Not sure what's going on...

**Comment by tiffon** [comment]
@jared-wallace Yeah, that's pretty strange. What you're seeing from VSCode is consistent with the output I'm seeing from `docker inspect <img-ID>` and seems to be the latest image.

On the other hand, pulling via `docker-compose pull` might not restart already running containers.

If you inspect the running docker container does it look like it's using the new image? 

```
$ docker ps -a | grep jaegertracing/all-in-one
7248eb09a2a6        jaegertracing/all-in-one:latest   "/go/bin/standalon..."   8 hours ago         Up 8 hours          0.0.0.0:5775->5775/udp, 0.0.0.0:5778->5778/tcp, 0.0.0.0:9411->9411/tcp, 0.0.0.0:14268->14268/tcp, 0.0.0.0:6831-6832->6831-6832/udp, 0.0.0.0:16686->16686/tcp   lucid_ptolemy

$ docker inspect 7248eb09a2a6 -f '{{.Image}}'
sha256:edcf7b4540c3d1801e184932a59a0e168d2107bd16e8acaec04eded2de2b02f9
```

**Comment by jared-wallace** [comment]
<img width="1259" alt="screen shot 2017-12-24 at 9 41 30 am" src="https://user-images.githubusercontent.com/6503051/34327622-ae2b45c6-e88e-11e7-86a2-c31fde85f3f7.png">

Mine seems to match

**Comment by jared-wallace** [comment]
You can close this now :) Browser cache for the win. (Opened a new private tab, and the problem is fixed)

Thanks for the quick and thorough assistance on this.

**Comment by yurishkuro** [comment]
not sure how browser cache could be responsible, each build gets a random suffix for the static html assets.

**Comment by tiffon** [comment]
@jared-wallace Hey, no problem. Glad we got to the bottom of it, or at least resolved it. (Nice PS1, too)

Yeah, not sure about the caching unless the html was being cached. Pretty sure that's served with a no-cache header. I'll double check.
